name: Quality Gate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0

    - name: Install dependencies
      run: npm i

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm t -- --coverage
